### ISSUE TITLE
Date Parse Error

### ISSUE THREAD

**Issue by schorschii** [rominf/winapps#10]
Hi,
when using list_installed() on a machine, I get the following error:
`ValueError: time data '7/30/2020' does not match format '%Y%m%d'`

It is caused by an Adobe program, which has an install date of `7/30/2020` set in registry.

Maybe the date parsing should be wrapped in a `try` to avoid crashing when the date is corrupt.

**Comment by rominf** [comment]
I don't have a Windows machine nowadays for testing. PR is welcome!

**Comment by schorschii** [comment]
It turned out that it is already fixed by this commit: https://github.com/rominf/winapps/commit/31978210d03e85a330710dcea4c3eb0d7def7223

I've used the latest version v0.1.6 from PyPI which throws the error.

**Comment by portikCoder** [comment]
I see that it is fixed, but cannot see any new release of that.

Are you going to have one?
