### ISSUE TITLE
Fixed dependencies from setup.py

### ISSUE THREAD

**Issue by QuentiumYT** [rominf/winapps#6]
Distutils is built in but doesn't support some arguments.
Importing setuptools at the beginning fixed this issue.

`C:\Users\-\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
C:\Users\-\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'extras_require'
  warnings.warn(msg)
C:\Users\-\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)`

Added a try/except in case the user don't have it installed. Fixed in #5 As well.

**Comment by rominf** [comment]
Thanks!
