### ISSUE TITLE
Cannot List the Installed Applications and Cannot Uninstall an Application

### ISSUE THREAD

**Issue by slalomchip** [rominf/winapps#7]
When I execute the following:

```
for app.name in winapps.list_installed():
    print(app.name, '\n')
```

several applications are listed and then I receive this traceback:

```
  File "<ipython-input-5-057ec1d232d1>", line 1, in <module>
    for app in winapps.search_installed('Notepad++ (32-bit x86)'):

  File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 53, in search_installed
    if not re.search(pattern=pattern, string=str(getattr(app, field_name, '')), flags=search_flags):

  File "C:\Users\slalo\Miniconda3\lib\re.py", line 183, in search
    return _compile(pattern, flags).search(string)

  File "C:\Users\slalo\Miniconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "C:\Users\slalo\Miniconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "C:\Users\slalo\Miniconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "C:\Users\slalo\Miniconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "C:\Users\slalo\Miniconda3\lib\sre_parse.py", line 654, in _parse
    source.tell() - here + len(this))

error: multiple repeat
```

Likewise, when I try to directly uninstall an application with this command:

`winapps.uninstall('OBS Studio', args=['/S'])`

I get this traceback:

```
  File "<ipython-input-2-d879c8e91f81>", line 1, in <module>
    winapps.uninstall('OBS Studio', args=['/S'])

  File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 72, in uninstall
    app.uninstall(*args)

  File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 36, in uninstall
    command()

  File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\commands\base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]

  File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\commands\base.py", line 231, in run
    with self.bgrun(args, **kwargs) as p:

  File "C:\Users\slalo\Miniconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)

  File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\commands\base.py", line 185, in bgrun
    p = self.popen(args, **kwargs)

  File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\commands\base.py", line 312, in popen
    return self.cmd.popen(self.args + list(args), **kwargs)

  File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\machines\local.py", line 131, in popen
    **kwargs)

  File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\machines\local.py", line 311, in _popen
    **kwargs)  # bufsize = 4096

  File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\machines\local.py", line 40, in __init__
    self._proc = Popen(*args, **kwargs)

  File "C:\Users\slalo\Miniconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\slalo\Miniconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)

  File "C:\Users\slalo\Miniconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

OSError: [WinError 740] The requested operation requires elevation
```

Is there any way around these errors or can applications that cause the errors be bypassed?

**Comment by thevickypedia** [comment]
> When I execute the following:
> 
> ```
> for app.name in winapps.list_installed():
>     print(app.name, '\n')
> ```
> 
> several applications are listed and then I receive this traceback:
> 
> ```
>   File "<ipython-input-5-057ec1d232d1>", line 1, in <module>
>     for app in winapps.search_installed('Notepad++ (32-bit x86)'):
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 53, in search_installed
>     if not re.search(pattern=pattern, string=str(getattr(app, field_name, '')), flags=search_flags):
> 
>   File "C:\Users\slalo\Miniconda3\lib\re.py", line 183, in search
>     return _compile(pattern, flags).search(string)
> 
>   File "C:\Users\slalo\Miniconda3\lib\re.py", line 286, in _compile
>     p = sre_compile.compile(pattern, flags)
> 
>   File "C:\Users\slalo\Miniconda3\lib\sre_compile.py", line 764, in compile
>     p = sre_parse.parse(p, flags)
> 
>   File "C:\Users\slalo\Miniconda3\lib\sre_parse.py", line 930, in parse
>     p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
> 
>   File "C:\Users\slalo\Miniconda3\lib\sre_parse.py", line 426, in _parse_sub
>     not nested and not items))
> 
>   File "C:\Users\slalo\Miniconda3\lib\sre_parse.py", line 654, in _parse
>     source.tell() - here + len(this))
> 
> error: multiple repeat
> ```
> 
> Likewise, when I try to directly uninstall an application with this command:
> 
> `winapps.uninstall('OBS Studio', args=['/S'])`
> 
> I get this traceback:
> 
> ```
>   File "<ipython-input-2-d879c8e91f81>", line 1, in <module>
>     winapps.uninstall('OBS Studio', args=['/S'])
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 72, in uninstall
>     app.uninstall(*args)
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 36, in uninstall
>     command()
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\commands\base.py", line 96, in __call__
>     return self.run(args, **kwargs)[1]
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\commands\base.py", line 231, in run
>     with self.bgrun(args, **kwargs) as p:
> 
>   File "C:\Users\slalo\Miniconda3\lib\contextlib.py", line 112, in __enter__
>     return next(self.gen)
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\commands\base.py", line 185, in bgrun
>     p = self.popen(args, **kwargs)
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\commands\base.py", line 312, in popen
>     return self.cmd.popen(self.args + list(args), **kwargs)
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\machines\local.py", line 131, in popen
>     **kwargs)
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\machines\local.py", line 311, in _popen
>     **kwargs)  # bufsize = 4096
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\plumbum\machines\local.py", line 40, in __init__
>     self._proc = Popen(*args, **kwargs)
> 
>   File "C:\Users\slalo\Miniconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
>     super(SubprocessPopen, self).__init__(*args, **kwargs)
> 
>   File "C:\Users\slalo\Miniconda3\lib\subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
> 
>   File "C:\Users\slalo\Miniconda3\lib\subprocess.py", line 1178, in _execute_child
>     startupinfo)
> 
> OSError: [WinError 740] The requested operation requires elevation
> ```
> 
> Is there any way around these errors or can applications that cause the errors be bypassed?

first of all, why you are you using ```for app.name in winapps.list_installed()``` ?
this is all you need.. app is an object and that is the reason why you add ```.name``` while printing so you get the string
This will work fine
```
for app in winapps.list_installed():
    print(app.name)
```

**Comment by rominf** [comment]
Hi. I don't longer have Windows machine, so I don't have plans to work on the library. PRs are welcome though.

**Comment by slalomchip** [comment]
Changing the script from 
```
for app.name in winapps.list_installed():
    print(app.name, '\n')
```
to 
```
for app in winapps.list_installed():
    print(app.name)
```
makes no difference.  I get the same result (tested).

**Comment by thevickypedia** [comment]
@slalomchip which version of winapps have you installed. I would say try to reinstall with pip or pip3. If still issues post the traceback here.

**Comment by slalomchip** [comment]
@thevickypedia - I'm running winapps 0.1.6  I installed it with pip last month.  I just now uninstalled it with pip and reinstalled it with pip and I get the same result.  The script successfully listed 69 applications before erroring.  On another Windows machine, the script executes without any issue.  Here is the traceback.

```
Traceback (most recent call last):

  File "<ipython-input-8-a486dadd9822>", line 1, in <module>
    for app in winapps.list_installed():

  File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 42, in <genexpr>
    return (application for application in application_or_none_generator if application is not None)

  File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 41, in <genexpr>
    for application_key in _installed_application_keys())

  File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 186, in _installed_application
    setattr(result, *f(value))

  File "C:\Users\slalo\Miniconda3\lib\site-packages\winapps\__init__.py", line 106, in <lambda>
    'install_date', _none_on_value_not_set(value) and datetime.strptime(value, '%Y%m%d').date()),

TypeError: strptime() argument 1 must be str, not int
```

**Comment by vonsjnr** [comment]
Yup, unfortunately i've got exactly the same error as @slalomchip

**Comment by thevickypedia** [comment]
honestly, I'm taking a vague guess here.. I've had a similar issue after installing `ChatterBot` due to version conflict with `json`
are you on a `venv`? If not, try to create one and see if it solves any version conflict, seems like this is coming from an object in `datetime` 
If a `venv` doesn't solve your problem I'm not sure of anything on top of my head.

**Comment by QuentiumYT** [comment]
@slalomchip I've created a PR that was merged a couple of month ago [here](https://github.com/rominf/winapps/pull/5)
The fix was not pushed to pypi because the owner don't have Windows anymore (cannot be found with pip).

You can install it by running `pip install --upgrade git+https://github.com/rominf/winapps.git#egg=winapps`
Or if you don't have git installed `pip install --upgrade https://github.com/rominf/winapps/tarball/master`

**Comment by slalomchip** [comment]
@QuentiumYT  - That fixed it for me!  Thanks!  

I'm not very familiar with the etiquette of closing issues when resolved and I don't know if this issue should be closed because the fix is not in the main branch.  Therefore, I'll leave it up to you on how the issue should be closed.

**Comment by QuentiumYT** [comment]
I cannot decide to close this issue as I'm not the repository owner, it's up to you :) But the main problem was solved so, I would close it.

**Comment by slalomchip** [comment]
@QuentiumYT  - OK.  With your fix, I'll close the issue.  Hopefully it will be implemented in the main branch.
